### ISSUE TITLE
BUG Fields in `anyOf` block get improperly handled

### ISSUE THREAD

**Issue by MickHarrigan** [jqnatividad/qsv#2170] opened 2024-09-25 22:43 UTC
**Describe the bug**
Cannot validate data in a csv as a number when the given schema has the value wrapped in an `anyOf` block.

**To Reproduce**
1. Build `qsv` from `cargo install qsv --locked --bin qsv --features feature_capable,apply,luau,fetch,foreach,to`
2. Use [schema_example.zip](https://github.com/user-attachments/files/17139249/schema_example.zip)
3. Run `cargo run` to build and create the `schema.json` via [`schemars`](https://docs.rs/schemars/1.0.0-alpha.15/schemars/index.html)
4. Run `qsv validate data.csv schema.json`
5. Open `data.csv.validation-errors.tsv`

**Expected behavior**
The `data.csv` is expected to be considered valid due to the presence of the `float` field being represented as a float, as well as the fields `x`, `y`, and `z` not being required due to being outside the current block within the `anyOf`.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - qsv 0.135.0-mimalloc-apply;fetch;foreach;Luau 0.640;to;-12-12;25.03 GiB-2.59 GiB-22.59 GiB-31.29 GiB (Unknown_target compiled with Rust 1.81) installed

**Comment by jqnatividad** [comment] 2024-09-26 03:52
Thanks for the report @MickHarrigan .

The `validate` command leverages the `[jsonschema](https://github.com/Stranger6667/jsonschema-rs)` crate. We use the Draft 2020-12 specification, and it appears this is a known issue per the bowtie compliance report:

https://github.com/Stranger6667/jsonschema-rs?tab=readme-ov-file#supported-drafts
https://bowtie.report/#/implementations/rust-jsonschema

Regardless, the intended use case I optimized `qsv validate` for is to use the JSON schema generated by the `qsv schema` command from a "training" CSV to validate similar CSVs using the same schema and I chose the jsonschema crate as its the fastest one I found in the rust ecosystem at the time.

`qsv validate` was never meant to be a generic JSON Schema validator.

Still, I'm hopeful that the `jsonschema` crate will eventually support `anyOf`, so qsv gets to use it.

cc @Stranger6667

**Comment by Stranger6667** [comment] 2024-09-26 06:07
I'll take a closer look at this issue once I finish the ongoing referencing logic overhaul. Thanks for tagging me

**Comment by Stranger6667** [comment] 2024-09-26 12:05
The issue is that the `float` property comes to `jsonschema` as `"1.0"` (a string) and therefore that object fails validation for both sub-validators inside `anyOf`.

Right now, `jsonschema` emits all validation errors which is confusing for combinators (similar cases go for `oneOf` and `allOf`). Probably a nicer way would be to find the "most relevant" sub-schema and show just its error, but it will require some rework in the error sub-system which I plan to work on later this year.

To conclude, on the `jsonschema` side it is a confusing error output, not a spec compliance.

**Comment by jqnatividad** [comment] 2024-09-26 13:24
Thanks @Stranger6667 for looking into this.

I may have to tweak the data type inferencing in validate so it correctly infers a float instead of a string for 1.0.

FYI, I use `qsv stats` to infer data types, and from there, create a JSON instance for each CSV record, which is then validated by `jsonschema`.

**Comment by MickHarrigan** [comment] 2024-09-26 16:25
> I may have to tweak the data type inferencing in validate so it correctly infers a float instead of a string for 1.0.

I just did some testing in my example and even with the value "1" it is not parsed as a number of any format, let alone a float.

> To conclude, on the `jsonschema` side it is a confusing error output, not a spec compliance.

And in this case if I make all the `f32` or values within the `anyOf` into strings things seem to work just fine.

**Comment by jqnatividad** [comment] 2024-09-27 01:27
After further investigation and as I explained earlier - `validate` was never meant to be a generic JSON schema validator and there is no instance I can think of when `anyOf` handling applies to CSV validation.

Closing this for now. Feel free to reopen @MickHarrigan if you can think of a case when `anyOf` would be useful for the CSV validation use case qsv is designed for.

FYI, I originally was looking for a Table Schema validator - as it was purpose-built for CSV validation.
https://specs.frictionlessdata.io//table-schema/

However, there are no implementations in the Rust ecosystem, and the python implementation was not performant enough for our data ingestion pipeline - https://github.com/frictionlessdata/tableschema-py

**Closed by jqnatividad** 2024-09-27 01:27 UTC
